name: WorldEdit-SE
main: tomo0611\WorldEditSE
version: 1.16.0+dev
api: [3.14.1]
load: STARTUP
author: tomo0611
description: World Editor !!
website: https://github.com/tomo0611/WorldEdit-SE
commands:
  wse:
    description: World Edit SE command
    usage: "/wse"
    aliases:
      - ws
      - wese
    permission: wse.command
permissions:
 wse:
  default: true
  description: "Allows using all features"
  children:
   wse.command:
    default: true
    description: "Allows using all the features commands"
    children:
     wse.command.pos1:
      default: true
      description: "Allows the set of pos1"