name: PMMP Action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      run: echo Hello, world! &&
        sudo apt-fast install git &&
        git clone https://github.com/pmmp/DevTools &&
        php -dphar.readonly=0 ./DevTools/src/DevTools/ConsoleScript.php --make $GITHUB_WORKSPACE --out ./WorldEditSE_${{ github.run_number }}.phar
    
    - uses: actions/upload-artifact@v2

    - name: Upload artifact
      with:
        name: Main Artifact
        path: ./WorldEditSE_${{ github.run_number }}.phar